name: deploy cfn to s3
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/s3.yaml'
      - 'cloudformation/*'

permissions:
  id-token: write
  contents: read

jobs:

  deploy_source:
    name: copy cfn to s3
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          role-to-assume: arn:aws:iam::329261680777:role/farssh-github
          role-session-name: github-action-copy-s3
          aws-region: eu-central-1
      - name: copy cfn to s3
        run: |
          aws s3 sync cloudformation/ s3://farssh/cloudformation/
