#!/bin/sh
set -e

echo ">>> FarSSH container image $FARSSH_VERSION ($FARSSH_DATE)"

# Generate motd with version and date
sed -i "s/__FARSSH_VERSION__/$FARSSH_VERSION/g" /etc/motd
sed -i "s/__FARSSH_DATE__/$FARSSH_DATE/g" /etc/motd

echo ">>> FarSSH host keys:"
printf '%s\n' "$FARSSH_SSH_HOST_ED25519_KEY_BASE64" | base64 -d > /etc/ssh/ssh_host_ed25519_key
chmod 600 /etc/ssh/ssh_host_ed25519_key
ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key

mkdir ~/.ssh
echo "$FARSSH_SSH_AUTHORIZED_KEYS" > ~/.ssh/authorized_keys
chmod -R go-rwx ~/.ssh

echo ">>> FarSSH authorized keys:"
ssh-keygen -lf ~/.ssh/authorized_keys

sed -i "s/#*Port .*/Port ${FARSSH_SSH_PORT}/" /etc/ssh/sshd_config

/farssh-terminator &

exec "$@"
